config/routes.rb
Bscsails::Application.routes.draw do
  devise_for :users
  resources :sails
  root 'sails#index'
end

app/models/sail.rb
class Sail < ActiveRecord::Base
  validates :when, presence: true
  validates :details, presence: true
  validates :user, presence: true
  validates :title, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :sails, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
end

app/controllers/sails_controller.rb
class SailsController < ApplicationController
  def index
    @sails = Sail.all
    @sails_by_date = @sails.group_by(&:when)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  # def index
  #   @articles = Article.all
  #   @articles_by_date = @articles.group_by(&:published_on)
  #   @date = params[:date] ? Date.parse(params[:date]) : Date.today
  # end

  def show
    @sail = Sail.find(params[:id])
  end

  def new
    @sail = Sail.new
  end

  def create
    @sail = Sail.new(sail_params)
    @sail.user = current_user
    if @sail.save
      redirect_to @sail, notice: "Created sail.  Please ensure you provided, at minimum, contact details and a time."
    else
      render :new
    end
  end

  def edit
    @sail = Sail.find(params[:id])
    if @sail.user != current_user
      redirect_to @sail, notice: "Sorry you can't edit other people's sails"
    end
  end

  def update
    @sail = Sail.find(params[:id])
    if @sail.update(sail_params)
      redirect_to @sail, notice: "Updated sail."
    else
      render :edit
    end
  end

  def destroy
    @sail = Sail.find(params[:id])
    @sail.destroy
    respond_to do |format|
      format.html { redirect_to sails_url, 
        notice: 'Deleted successfully' }
      format.json { head :no_content }
    end
  end

  private

  def sail_params
    params.require(:sail)
      .permit(:title, :when, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BSC Sails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  
</body>
</html>

app/views/sails/_form.html.erb
<%= form_for @sail do |f| %>
  <% if @sail.errors.full_messages.count > 0 %>
    <ul>
      <% @sail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.text_field :when %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sails/edit.html.erb
<h1>Edit Sail  |  
<%= link_to "Delete", sail_path(@sail),
          method: :delete %></h1>

<%= render 'form' %>

<p><%= link_to "Back to Sails", sails_path %></p>

app/views/sails/index.html.erb
<div id="header"><h2>Boston Sailing Center Sails</h2></div>
<div id="logo"><%= image_tag("sail-logo.jpg") %></div><br>

<div id="sails">
  <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @sails_by_date[date] %>
      <ul>
        <% @sails_by_date[date].each do |sail| %>
          <li><%= link_to sail.title, sail %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>


<p><%= link_to "New Sail", new_sail_path %>  |  
  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path%>  |  
    <%= link_to "Sign In", new_user_session_path %>
  <%end%></p>

app/views/sails/new.html.erb
<h1>New Sail</h1>

<%= render 'form' %>

<p><%= link_to "Back to Sails", sails_path %></p>

app/views/sails/show.html.erb
<h1><%= @sail.title %></h1>

<p class="info">Created on <%= @sail.created_at.strftime("%B %e, %Y") %></p>

<%= simple_format @sail.when.strftime("%B %e, %Y") %>
<%= simple_format @sail.details %>

<p>
  <%= link_to "Edit Sail", edit_sail_path(@sail) %> |
  <%= link_to "Back to Sails", sails_path %>
</p>